esphome:
  includes:
    - CustomSensor_Adafruit_PCT2075.h
  libraries:
    - "Adafruit PCT2075"

sensor:
  - platform: custom
    lambda: |-
      auto my_PCT2075 = new CustomPCT2075Temp();
      App.register_component(my_PCT2075);
      return {my_PCT2075};
      
    sensors:
      name: "PCT2075 Temperature"
      unit_of_measurement: "°C"
      accuracy_decimals: 2
